# --- Type ---
- name: bug
  color: "d73a4a"
  description: Something isn't working
- name: enhancement
  color: "a2eeef"
  description: New feature or request
- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation
- name: chore
  color: "fef2c0"
  description: Maintenance and housekeeping
- name: refactor
  color: "d4c5f9"
  description: Code improvement without behavior change
- name: question
  color: "d876e3"
  description: Further information is requested
- name: duplicate
  color: "cfd3d7"
  description: This issue or pull request already exists
- name: invalid
  color: "e4e669"
  description: "This doesn't seem right"
- name: wontfix
  color: "ffffff"
  description: This will not be worked on

# --- Component ---
- name: "component:extract"
  color: "1d76db"
  description: Scraping and extraction (extract.mjs)
- name: "component:summarize"
  color: "5319e7"
  description: AI summarization (summarize.mjs)
- name: "component:docs"
  color: "0e8a16"
  description: Generated documentation output

# --- Priority ---
- name: "priority:critical"
  color: "b60205"
  description: Must be fixed immediately
- name: "priority:high"
  color: "d93f0b"
  description: Important — fix soon
- name: "priority:medium"
  color: "fbca04"
  description: Normal priority
- name: "priority:low"
  color: "c2e0c6"
  description: Nice to have

# --- Status ---
- name: blocked
  color: "b60205"
  description: Blocked by another issue or external dependency
- name: in-progress
  color: "0e8a16"
  description: Actively being worked on
- name: needs-repro
  color: "fbca04"
  description: Needs a reproducible example
- name: needs-review
  color: "7057ff"
  description: Waiting for review

# --- Effort ---
- name: "effort:small"
  color: "c2e0c6"
  description: "Quick fix — less than an hour"
- name: "effort:medium"
  color: "fbca04"
  description: "A few hours of work"
- name: "effort:large"
  color: "d93f0b"
  description: "Significant effort — a day or more"

# --- Dependency ---
- name: dependencies
  color: "0366d6"
  description: Pull requests that update a dependency
- name: npm
  color: "cb2431"
  description: npm ecosystem dependency
- name: github-actions
  color: "000000"
  description: GitHub Actions dependency

# --- Special ---
- name: "help wanted"
  color: "008672"
  description: Extra attention is needed
- name: pinned
  color: "006b75"
  description: Pinned — exempt from stale bot
- name: security
  color: "ee0701"
  description: Security-related issue
- name: stale
  color: "ededed"
  description: No recent activity
- name: breaking
  color: "b60205"
  description: Introduces a breaking change
- name: automation
  color: "bfd4f2"
  description: CI/CD and GitHub Actions
