name: Feature Request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches did you consider?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the tool would this affect?
      options:
        - Extract (extract.mjs)
        - Summarize (summarize.mjs)
        - Documentation output
        - CI / GitHub Actions
        - Other
    validations:
      required: true
